name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username hdhoma --password ${{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}} ghcr.io
                docker build -t ghcr.io/hdhoma/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/hdhoma/arithmetic-service:latest
